### ISSUE TITLE
Version 2.0 - Hurricane

### ISSUE THREAD

**Issue by franciscop** [umbrellajs/umbrella#40]
These are the expected breaking changes for version 2.0. Please feel free to request anything else here.

- [x] **Sane <strike>Francis</strike> AJAX #34**: before it only accepted POST and was quite limited. Make it more flexible but not bloated.
- [x] **Better `.serialize()` #35**: make it work better with all kinds of elements and disabled properties
- [x] **New method `.array()` #42** and maybe other similar ones.
- [x] **New method `.handle()`** (`.on()` + `e.preventDefault()` all in one).
- [x] **Normal `.prepend()` and `.after()` order #43**.
- [x] **Document the HTML generator**, which is *quite* powerful and consider making it better with @tr3intaydos suggestions in #20

**Comment by franciscop** [comment]
External libraries are deleted. I'm happy with the way it is now. Maybe a tutorial could be written, but it's not worth to add it.
